### ISSUE TITLE
Unable to login with credentials against NiFi 1.0.1 (SSL/username+password)

### ISSUE THREAD

**Issue by bbossola-tesco** [hermannpencole/nifi-config#13]
This exception lands on the command line:

```
2017-08-29 15:23:17 | ERROR | [main] c.g.h.n.c.Main:141 - java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@36a19cc5
com.github.hermannpencole.nifi.swagger.ApiException: java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@36a19cc5
        at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:992)
        at com.github.hermannpencole.nifi.swagger.client.AccessApi.createAccessTokenWithHttpInfo(AccessApi.java:140)
        at com.github.hermannpencole.nifi.swagger.client.AccessApi.createAccessToken(AccessApi.java:125)
        at com.github.hermannpencole.nifi.config.service.AccessService.addTokenOnConfiguration(AccessService.java:36)
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:114)
Caused by: java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@36a19cc5
        at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
        at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
        at com.squareup.okhttp.Call.getResponse(Call.java:287)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:204)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:988)
        ... 4 common frames omitted
Caused by: java.io.EOFException: \n not found: size=0 content=...
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
        at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        ... 16 common frames omitted
Exception in thread "main" com.github.hermannpencole.nifi.config.model.ConfigException: java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@36a19cc5: null
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:142)
Caused by: com.github.hermannpencole.nifi.swagger.ApiException: java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@36a19cc5
        at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:992)
        at com.github.hermannpencole.nifi.swagger.client.AccessApi.createAccessTokenWithHttpInfo(AccessApi.java:140)
        at com.github.hermannpencole.nifi.swagger.client.AccessApi.createAccessToken(AccessApi.java:125)
        at com.github.hermannpencole.nifi.config.service.AccessService.addTokenOnConfiguration(AccessService.java:36)
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:114)
Caused by: java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@36a19cc5
        at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
        at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
        at com.squareup.okhttp.Call.getResponse(Call.java:287)
       at com.squareup.okhttp.Call.getResponse(Call.java:287)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:204)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:988)
        ... 4 more
Caused by: java.io.EOFException: \n not found: size=0 content=...
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
        at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        ... 16 more
```

I will keep investigating the issue on my side tomorrow. I can confirm that the same call made via a Python script works,

**Comment by bbossola-tesco** [comment]
Successful Python call (courtesy of my colleagues):

```
#!/usr/bin/env` python
import sys, urllib, urllib2

user = sys.argv[1]
passwd = sys.argv[2]

# endable urllib2 debug
handler = urllib2.HTTPSHandler(debuglevel=1)
opener = urllib2.build_opener(handler)
urllib2.install_opener(opener)

url = "https://our-server:8079/nifi-api/access/token"
headers = {"Content-type": "application/x-www-form-urlencoded",
           "Accept": "text/plain",
           "User-Agent": "Swagger-Codegen/1.1.0/java"}
data = urllib.urlencode({"password": passwd, "username": user})

try:
    request = urllib2.Request(url, data, headers)
    response = urllib2.urlopen(request)
    print response.read()
except urllib2.HTTPError as e:
    print e
    print e.read()
```

**Comment by hermannpencole** [comment]
Hello,
I don't reproduce this issue with nifi 1.0.1 ssl activated and ldap configured.
You can see more information about this problem on https://github.com/square/okhttp/issues/1517
If i don't reproduce the issue, it's difficult for me to help you.

**Comment by bbossola-tesco** [comment]
I understand, thanks for the pointer, I will look into that and come back to you.

**Comment by bbossola-tesco** [comment]
Update - I updated the nifi-swagger-client to use client okhttplib3 but no luck, the behavior is unchanged - investigation still ongoing

**Comment by bbossola-tesco** [comment]
Okay, the problem behind this is due to the underlying swagger-client-library not setting any timeout on the underlying OkHttpClient. As our LDAP server is slow, the library closes the call before the server has a chance to answer, causing all sort of different (and weird) behaviours, including the one reported,

We patched the problem with sample code, from this:
```
    public ApiClient() {
        httpClient = new OkHttpClient();
```

To this:
```
    public ApiClient() {
        httpClient = new OkHttpClient();
        httpClient.setConnectTimeout(Integer.getInteger("http.connect.timeout", 5), TimeUnit.SECONDS);* 
        httpClient.setReadTimeout(Integer.getInteger("http.read.timeout", 60), TimeUnit.SECONDS);*    
```
Let me know if you want me to contribute with a proper PR to the swagger library: we definitely need a fix to this problem in order to continue to use this library.

**Comment by bbossola-tesco** [comment]
On my cloned repos:
https://github.com/bbossola-tesco/nifi-config/tree/patch-issue-13
https://github.com/bbossola-tesco/nifi-swagger-client/tree/patch-issue-13

**Comment by hermannpencole** [comment]
Great news !
Nifi-config uses already a configuration of ConnectTimeout with a default of 10 seconds.
In order to do it the same way, i will add
 - on Nifi-config a configuration of ReadTimeOut with a default of 60 seconds
 - on Nifi-swagger-client a getter/setter for ReadTimeOut

**Comment by hermannpencole** [comment]
The version 1.1.11 have readTimeout and writeTimeout options (both with a default of 10 seconds).

**Comment by AlvinCJin** [comment]
I got the exact same issue with a secured NiFi cluster authorized by Kerberos.
java -jar nifi-deploy-config-1.1.12.jar \
-user name \
-password pwd \
-nifi http://hostname:port/nifi-api \
-branch "root>" \
-conf api-deploy-demo.xml \
-mode deployTemplate \
-readTimeout 60 \
-writeTimeout 60

Did I set anything wrong in above command?

2017-09-19 12:31:11 | INFO  | [main] c.g.h.n.c.Main:96 - Starting config_nifi 1.1.12 on mode deployTemplate
2017-09-19 12:31:12 | ERROR | [main] c.g.h.n.c.Main:147 - java.net.SocketTimeoutException: Read timed out
com.github.hermannpencole.nifi.swagger.ApiException: java.net.SocketTimeoutException: Read timed out
        at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:1030)
        at com.github.hermannpencole.nifi.swagger.client.AccessApi.createAccessTokenWithHttpInfo(AccessApi.java:140)
        at com.github.hermannpencole.nifi.swagger.client.AccessApi.createAccessToken(AccessApi.java:125)
        at com.github.hermannpencole.nifi.config.service.AccessService.addTokenOnConfiguration(AccessService.java:36)
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:120)

Thanks.
