### ISSUE TITLE
Null Pointer Exception on updateConfig

### ISSUE THREAD

**Issue by mattyait** [hermannpencole/nifi-config#28]
I'm trying to do updateConfig using nifi-deploy jar, it's throwing null pointer execption on createRoutes parts
2017-11-27 15:48:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:199 - Updated : IdentifyMimeType                      
2017-11-27 15:48:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:169 - Update processor : ListFile                     
2017-11-27 15:48:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:199 - Updated : ListFile                              
2017-11-27 15:48:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:169 - Update processor : PutFile                      
2017-11-27 15:48:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:199 - Updated : PutFile                               
Exception in thread "main" java.lang.NullPointerException                                                                     
        at com.github.hermannpencole.nifi.config.service.CreateRouteService.createRoutes(CreateRouteService.java:316)         
        at com.github.hermannpencole.nifi.config.service.UpdateProcessorService.updateByBranch(UpdateProcessorService.java:94)
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:129)                                                     

If i commented createRouteService.createRoutes(connections, optionNoStartProcessors); this line and create jar then it's not giving any error.However I want to use the original one so that I can create connection whenever I added in json.

**Comment by hermannpencole** [comment]
Hi, you must use an old version because there is no code on line 316 for CreateRouteService.java
Exception in thread "main" java.lang.NullPointerException
at com.github.hermannpencole.nifi.config.service.CreateRouteService.createRoutes(**CreateRouteService.java:316**)
at

**Comment by hermannpencole** [comment]
This issue is already fixed on : #26
