### ISSUE TITLE
Cannot position elements in process groups that contain connections

### ISSUE THREAD

**Issue by ennui93** [hermannpencole/nifi-config#32]
Looks like 72ac7a49c777ff0d32f9665770fb98cd3c386135 introduced a `NullPointerException` when attempting to place elements in a process group with connections, as `ConnectionEntity`s have null position. Observed in both NiFi 1.0.0 and 1.3.0.

```java -Dfile.encoding=UTF-8 -jar nifi-deploy-config-1.1.18-SNAPSHOT.jar -nifi http://localhost:8079/nifi-api -branch "root > an_input_port" -c an_input_port.xml -m deployTemplate
2017-12-07 14:03:49 | INFO  | [main] c.g.h.n.c.Main:99 - Starting config_nifi 1.1.18-SNAPSHOT on mode deployTemplate
2017-12-07 14:03:50 | INFO  | [main] c.g.h.n.c.Main:128 - Communicate with nifi 1.3.0
Exception in thread "main" java.lang.NullPointerException
	at com.github.hermannpencole.nifi.config.service.ProcessGroupService.lambda$findOtherPositionInPlace$11(ProcessGroupService.java:333)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.github.hermannpencole.nifi.config.service.ProcessGroupService.findOtherPositionInPlace(ProcessGroupService.java:335)
	at com.github.hermannpencole.nifi.config.service.ProcessGroupService.getNextPosition(ProcessGroupService.java:313)
	at com.github.hermannpencole.nifi.config.service.ProcessGroupService.createDirectory(ProcessGroupService.java:87)
	at com.github.hermannpencole.nifi.config.service.TemplateService.installOnBranch(TemplateService.java:69)
	at com.github.hermannpencole.nifi.config.Main.main(Main.java:142)

Process finished with exit code 1

**Comment by hermannpencole** [comment]
In version 1.1.18, i protected the code against null positionDto in the list of posittion.
thanks.

**Comment by ennui93** [comment]
Confirmed fixed. Thanks!
