### ISSUE TITLE
Cannot stop running input port in undeploy mode

### ISSUE THREAD

**Issue by ennui93** [hermannpencole/nifi-config#33]
When running nifi-config in the `undeploy` mode, it is not possible to stop a running input port.

```java -jar nifi-deploy-config-1.1.20-SNAPSHOT.jar -nifi http://localhost:8079/nifi-api -branch "root > an_input_port" -m undeploy
2017-12-08 12:57:38 | INFO  | [main] c.g.h.n.c.Main:109 - Starting config_nifi 1.1.20-SNAPSHOT on mode undeploy
2017-12-08 12:57:39 | INFO  | [main] c.g.h.n.c.Main:131 - Communicate with nifi 1.0.0
Exception in thread "main" com.github.hermannpencole.nifi.config.model.ConfigException: Conflict: 30f99d15-0160-1000-658a-827818fa5899 is not stopped
	at com.github.hermannpencole.nifi.config.service.PortService.lambda$setState$0(PortService.java:102)
	at com.github.hermannpencole.nifi.config.utils.FunctionUtils.runWhile(FunctionUtils.java:54)
	at com.github.hermannpencole.nifi.config.utils.FunctionUtils.lambda$runWhile$0(FunctionUtils.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.hermannpencole.nifi.swagger.ApiException: Conflict
	at com.github.hermannpencole.nifi.swagger.ApiClient.handleResponse(ApiClient.java:1104)
	at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:1027)
	at com.github.hermannpencole.nifi.swagger.client.InputPortsApi.updateInputPortWithHttpInfo(InputPortsApi.java:394)
	at com.github.hermannpencole.nifi.swagger.client.InputPortsApi.updateInputPort(InputPortsApi.java:379)
	at com.github.hermannpencole.nifi.config.service.PortService.lambda$setState$0(PortService.java:94)
	... 7 more

Process finished with exit code 1

**Comment by ennui93** [comment]
Not certain of the root cause, but I noticed there are some additional fields in the JSON sent by `nifi-swagger-client`:

```PUT /nifi-api/input-ports/30f99d15-0160-1000-658a-827818fa5899 HTTP/1.1
Accept: application/json
User-Agent: Swagger-Codegen/1.1.0/java
Content-Type: application/json; charset=utf-8
Content-Length: 207
Host: localhost:8079
Connection: Keep-Alive
Accept-Encoding: gzip

{"revision":{"version":1},"bulletins":[],"component":{"id":"30f99d15-0160-1000-658a-827818fa5899","state":"STOPPED","transmitting":false,"userAccessControl":[],"groupAccessControl":[],"validationErrors":[]}}```

**Comment by ennui93** [comment]
vs. those sent by the front-end via a browser:

```Host: 127.0.0.1:8079
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8079/nifi/
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Content-Length: 152
DNT: 1
Connection: keep-alive
{"revision":{"clientId":"35f69c9b-0160-1000-180f-de1e8960eef3","version":1},"component":{"id":"30f99d15-0160-1000-658a-827818fa5899","state":"STOPPED"}}

**Comment by hermannpencole** [comment]
thanks,
in version 1.1.20 I force some value to null
```java
 body.setBulletins(null);
 body.getComponent().setTransmitting(null);
 body.getComponent().setUserAccessControl(null);
 body.getComponent().setGroupAccessControl(null);
 body.getComponent().setValidationErrors(null);
```
and nifi-config can now stop port.

**Comment by hermannpencole** [comment]
There was a problem with oss.sonatype.org and version 1.1.20 did not have a binary.
I recreated a new version: 1.1.21

**Comment by ennui93** [comment]
Confirmed fixed. Thanks!
