### ISSUE TITLE
Null pointer exception on config update

### ISSUE THREAD

**Issue by Dagon-** [hermannpencole/nifi-config#38]
I'm testing out 1.1.31 which was working very well until I hit the following exception trying to update a config

Process:
- Push two templates
- Pull config
- Add a connection to config.json:
``` 
"connections": [
    {
      "name": "test_connection",
      "source": "root > SimulateDataMinrAlerts",
      "destination": "root > Publish_to_Kafka "
    }
  ],
```
- Run update config:

```2018-01-12 15:51:29 | INFO  | [main] c.g.h.n.c.Main:109 - Starting config_nifi 1.1.31 on mode updateConfig
2018-01-12 15:51:29 | INFO  | [main] c.g.h.n.c.Main:132 - Communicate with nifi 1.4.0
2018-01-12 15:51:29 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:66 - Processing : config.json
2018-01-12 15:51:30 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  Listen on ip:8123/dataminr (fb775b49-fb5c-3143-8941-3acbcc51b4bf) is already STOPPED
2018-01-12 15:51:30 | INFO  | [main] c.g.h.n.c.s.PortService:65 -  input (d5398d95-4877-300e-8dd5-8f7bc055b47b) is already STOPPED
2018-01-12 15:51:30 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  ConsumeKafka (ae5c25c6-bf14-3cda-8763-5aa7e6c51907) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.PortService:65 -  Dataminr Alerts (b33bcebd-f820-35c3-9e1c-d6024cbb9784) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  PublishKafka (46404dd1-e9d9-33f8-8887-a5cc17753c82) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  SimulateDataMinrAlertsFailures (10f7de65-c07b-31eb-b8c9-3266d809aa28) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  SimulateDataminr (df373b6f-1a5f-3309-a02c-14bae056ee78) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  Send Http Response to client (8da0147b-03a4-3fa3-9db5-01046b830400) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  LogAttribute (593ef047-2f06-3148-adc3-3a7d36637445) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  LogAttribute (f8686ee4-778a-3450-a686-c31d87d7ec97) is already STOPPED
2018-01-12 15:51:31 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  Listen on ip:8123/dataminr (fb775b49-fb5c-3143-8941-3acbcc51b4bf) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  Send Http Response to client (8da0147b-03a4-3fa3-9db5-01046b830400) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  SimulateDataMinrAlertsFailures (10f7de65-c07b-31eb-b8c9-3266d809aa28) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  SimulateDataminr (df373b6f-1a5f-3309-a02c-14bae056ee78) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.PortService:65 -  Dataminr Alerts (b33bcebd-f820-35c3-9e1c-d6024cbb9784) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.PortService:65 -  input (d5398d95-4877-300e-8dd5-8f7bc055b47b) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  ConsumeKafka (ae5c25c6-bf14-3cda-8763-5aa7e6c51907) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  LogAttribute (593ef047-2f06-3148-adc3-3a7d36637445) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  PublishKafka (46404dd1-e9d9-33f8-8887-a5cc17753c82) is already STOPPED
2018-01-12 15:51:32 | INFO  | [main] c.g.h.n.c.s.ProcessorService:56 -  LogAttribute (f8686ee4-778a-3450-a686-c31d87d7ec97) is already STOPPED
2018-01-12 15:51:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:76 - [root] is stopped
2018-01-12 15:51:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor Listen on ip:8123/dataminr (fb775b49-fb5c-3143-8941-3acbcc51b4bf) 
2018-01-12 15:51:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor Listen on ip:8123/dataminr (fb775b49-fb5c-3143-8941-3acbcc51b4bf) have config updated 
2018-01-12 15:51:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor SimulateDataMinrAlertsFailures (10f7de65-c07b-31eb-b8c9-3266d809aa28) 
2018-01-12 15:51:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor SimulateDataMinrAlertsFailures (10f7de65-c07b-31eb-b8c9-3266d809aa28) have config updated 
2018-01-12 15:51:33 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor SimulateDataminr (df373b6f-1a5f-3309-a02c-14bae056ee78) 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor SimulateDataminr (df373b6f-1a5f-3309-a02c-14bae056ee78) have config updated 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor Send Http Response to client (8da0147b-03a4-3fa3-9db5-01046b830400) 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor Send Http Response to client (8da0147b-03a4-3fa3-9db5-01046b830400) have config updated 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor LogAttribute (593ef047-2f06-3148-adc3-3a7d36637445) 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor LogAttribute (593ef047-2f06-3148-adc3-3a7d36637445) have config updated 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor PublishKafka (46404dd1-e9d9-33f8-8887-a5cc17753c82) 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor PublishKafka (46404dd1-e9d9-33f8-8887-a5cc17753c82) have config updated 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor LogAttribute (593ef047-2f06-3148-adc3-3a7d36637445) 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor LogAttribute (593ef047-2f06-3148-adc3-3a7d36637445) have config updated 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:288 - Update config processor ConsumeKafka (ae5c25c6-bf14-3cda-8763-5aa7e6c51907) 
2018-01-12 15:51:34 | INFO  | [main] c.g.h.n.c.s.UpdateProcessorService:320 - Processor ConsumeKafka (ae5c25c6-bf14-3cda-8763-5aa7e6c51907) have config updated 
Exception in thread "main" java.lang.NullPointerException
	at com.github.hermannpencole.nifi.config.service.UpdateProcessorService.updateControllers(UpdateProcessorService.java:149)
	at com.github.hermannpencole.nifi.config.service.UpdateProcessorService.updateByBranch(UpdateProcessorService.java:88)
	at com.github.hermannpencole.nifi.config.Main.main(Main.java:137)
```

I see there was a previous issue #26, am I misreading that this should have been fixed or is this something different?

**Comment by hermannpencole** [comment]
Hello,
it's not the same problem as # 36.
Do you have multiple controllers with the same name in one of the templates?
