### ISSUE TITLE
Cannot undeploy a template

### ISSUE THREAD

**Issue by bbossola-tesco** [hermannpencole/nifi-config#5]
It appears to be impossible to undeploy a template issuing the command with the specified mode. It looks like NiFi is validating the version is sent (the client sends "0") and thus refuses to undeploy.

$ java -jar target/nifi-deploy-config-1.1.3.jar -nifi http://localhost:8080/nifi-api -branch "root > Penguins" -m undeploy
2017-07-25 15:52:04 | INFO  | [main] c.g.h.n.c.Main:78 - Starting config_nifi 1.1.3 on mode undeploy
2017-07-25 15:52:04 | INFO  | [main] c.g.h.n.c.Main:98 - Communicate with nifi 1.3.0
2017-07-25 15:52:05 | ERROR | [main] c.g.h.n.c.Main:121 - Bad Request
com.github.hermannpencole.nifi.swagger.ApiException: Bad Request
        at com.github.hermannpencole.nifi.swagger.ApiClient.handleResponse(ApiClient.java:1066)
        at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:989)
        at com.github.hermannpencole.nifi.swagger.client.ProcessGroupsApi.removeProcessGroupWithHttpInfo(ProcessGroupsApi.java:2882)
        at com.github.hermannpencole.nifi.swagger.client.ProcessGroupsApi.removeProcessGroup(ProcessGroupsApi.java:2866)
        at com.github.hermannpencole.nifi.config.service.TemplateService.undeploy(TemplateService.java:90)
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:116)
Exception in thread "main" com.github.hermannpencole.nifi.config.model.ConfigException: Bad Request: [0, 283c9480-82d8-45d4-b0d2-3985d6ac769f, 7a2d55b8-015d-1000-e273-e7e029df9450] is not the most up-to-date revision. This component appears to have been modified
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:122)
Caused by: com.github.hermannpencole.nifi.swagger.ApiException: Bad Request
        at com.github.hermannpencole.nifi.swagger.ApiClient.handleResponse(ApiClient.java:1066)
        at com.github.hermannpencole.nifi.swagger.ApiClient.execute(ApiClient.java:989)
        at com.github.hermannpencole.nifi.swagger.client.ProcessGroupsApi.removeProcessGroupWithHttpInfo(ProcessGroupsApi.java:2882)
        at com.github.hermannpencole.nifi.swagger.client.ProcessGroupsApi.removeProcessGroup(ProcessGroupsApi.java:2866)
        at com.github.hermannpencole.nifi.config.service.TemplateService.undeploy(TemplateService.java:90)
        at com.github.hermannpencole.nifi.config.Main.main(Main.java:116)

Do you have any workaround?

**Comment by hermannpencole** [comment]
Hi, 
I look at this problem this week
thanks

**Comment by bbossola-tesco** [comment]
NiFi Version: 
1.3.0
06/05/2017 12:31:48 BST
Tagged nifi-1.3.0-RC1

Java version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by hermannpencole** [comment]
Release 1.1.4 is created and have the correction (It is necessary to wait that oss.sonatype.org deploy the release on maven central).
If the correction is ok for you, close the issue. If not say what is wrong.

**Comment by bbossola-tesco** [comment]
Thanks, verified already with the snapshot, everything works :)
